[tg.bot]
token = "1234567890:ABCDEFGHIJKLMNOPQ-RSTUVWXYZabcdefgh"

[ai.api]
url = "https://api.siliconflow.cn/v1/chat/completions"
token = "sk-abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv"
model = "deepseek-ai/DeepSeek-V3"

[tarot.ai]
prompt = "请在接下来使用中文根据我的问题和我抽取到的塔罗牌进行回答。"
