services:
  linquebot:
    container_name: linquebot
    restart: unless-stopped
    depends_on:
      pgvector:
        condition: service_healthy
      ollama:
        condition: service_started
      ollama-init:
        condition: service_completed_successfully
    image: ghcr.io/lhcfl/linquebot_rs
    volumes:
      - ./app:/app
    environment:
      - VECTOR_DATABASE_URL=postgres://postgres:123456@pgvector:5432/linquebot
      - OLLAMA_EMBEDDING_API_URL=http://ollama:11434/api/embeddings

  pgvector:
    image: ghcr.io/tensorchord/pgvecto-rs:pg17-v0.4.0
    # ports:
    #   - 5433:5432 # For local development, uncomment to expose port
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: linquebot
      POSTGRES_PASSWORD: "123456"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    # ports:
    #   - 11434:11434 # For local development, uncomment to expose port

  ollama-init:
    container_name: ollama-init
    image: ollama/ollama
    command: ["pull", "snowflake-arctic-embed2"]
    environment:
      - OLLAMA_HOST=ollama:11434
    depends_on:
      ollama:
        condition: service_started

volumes:
  pgvector_data:
    driver: local
  ollama_data:
    driver: local
