name: Build with Nix

on:
  workflow_dispatch:
  push:

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: beiyanyunyi
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Print flake metadata
        run: nix flake metadata --accept-flake-config

      - name: Build
        run: |
          NIXPKGS_ALLOW_UNFREE=1 nix build .#dockerImage --accept-flake-config

      - name: docker load
        run: |
          docker load < ./result

      - name: docker auth
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u lhcfl --password-stdin

      - name: retag to latest
        if: github.ref_name == 'main'
        run: |
          docker tag ghcr.io/lhcfl/linquebot_rs:nix-built ghcr.io/lhcfl/linquebot_rs:latest

      - name: docker push to latest
        if: github.ref_name == 'main'
        run: |
          docker push ghcr.io/lhcfl/linquebot_rs:latest

      - name: retag to tag
        if: github.ref_name != 'main'
        run: |
          REF=${{ github.ref_name }}
          docker tag ghcr.io/lhcfl/linquebot_rs:nix-built ghcr.io/lhcfl/linquebot_rs:${REF//\//-}

      - name: docker push to tag
        if: github.ref_name != 'main'
        run: |
          REF=${{ github.ref_name }}
          docker push ghcr.io/lhcfl/linquebot_rs:${REF//\//-}

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: result
      #     path: |
      #       result
