name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build -r --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: |
            target/release/linquebot_rs
