name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Clippy
        run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu clippy
      - name: Run Clippy
        run: RUSTFLAGS=-Dwarnings cargo clippy --features "bundle_duckdb"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build -r --verbose --features "bundle_duckdb"
      - name: Run tests
        run: cargo test --verbose --features "bundle_duckdb"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: |
            target/release/linquebot_rs
